### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by cexbrayat** [briebug/cypress-schematic#32]
**Describe the bug**

I encountered the same issue mentioned in #22 but while trying to reproduce, I realize that it might be more profound. It looks like any TS syntax in a spec throws an error.

**To Reproduce**
```
npx @angular/cli new cypress-ts --defaults
cd cypress-ts
ng add @briebug/cypress-schematic --remove-protractor
ng e2e
# works great!
```

Now edit `spec.ts` to have a bit of TS syntax:

```typescript
const home: string = "http://localhost:4200";
cy.visit(home);
```

Now Cypress throws:
```
const home: string = "http://localhost:4200";
            ^
ParseError: Unexpected token
```

The same happens with an import, with the error mentioned in #22 

**Expected behavior**

It should support TS syntax in specs

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 80

**Comment by anthonymjones** [comment]
Hi @cexbrayat, thank you for bringing this to our attention! We'll get working on it.

**Comment by MrCube42** [comment]
@anthonymjones I had a first look into this: I think the problem is that Cypress does not fully support TypeScript out-of-the-box (https://github.com/cypress-io/cypress/issues/1859). Currently Cypress accepts `.ts` files and the schematic already sets up everything for the IDE (like VSCode) to work. However, TypeScript itself can not be used during executing because it is not transpiled by default.

In order to to this, we need to add a preprocessor (like described here https://docs.cypress.io/guides/tooling/typescript-support.html#Transpiling-TypeScript-test-files). Luckily Gleb already wrote an npm package to do this called `@bahmutov/add-typescript-to-cypress` (https://github.com/bahmutov/add-typescript-to-cypress).

My plan is to do the following:
- Make sure that adding `@bahmutov/add-typescript-to-cypress` after the repo steps fixes the problem
- Use this as a first workaround whenever a quick fix is needed
- Integrate the preprocessor into the schematic which should fix the problem

**Comment by MrCube42** [comment]
Workaround for the time being:
- Run the repro like described above (so, use the schematic and use types in your spec)
- Adding `npm install --save-dev @bahmutov/add-typescript-to-cypress` fixes the problem

I'll create a PR that tries to integrate this into the schematic by default.

**Comment by cexbrayat** [comment]
Awesome job, I just tested the latest release, and it works perfectly, thank you!

**Comment by anthonymjones** [comment]
Thank you for testing it, @cexbrayat!

**Comment by michaeljota** [comment]
Now that TS is supported out-the-box by Cypress, do we still need to apply the preprocessor fix? Maybe we could remove this, so the integration between TS and Cypress is the Cypress one.
