### ISSUE TITLE
Cannot install the application with "ng new @briebug/cypress-schematic"

### ISSUE THREAD

**Issue by rasztaszilvi** [briebug/cypress-schematic#41]
Hi, I tried to install the Angular application based on the Pluralsight conference "ng-conf '19: Testing Is a Black Hole of Time and Effort: Avoiding the Suck Using Cypress" but I could not install the application under test (only the Cypress)

**To Reproduce**
1. Create a new folder
2. Type $ng new @briebug/cypress-schematic
3. See error:

Schematic input does not validate against the Schema: {"name":"@briebug/cypress-schematic","version":"9.1.3"}
Errors:

  Data path ".name" should match format "html-selector".

**Expected behavior**
App is installed 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.2

**Additional context**
I can also not install it any other way (just empty angular)
Cypress can be installed from bit.ly/ngcy

**Comment by anthonymjones** [comment]
Hi @rasztaszilvi, I'd like to understand your issue better. Are you wanting to create a new Angular application that uses Cypress instead of Protractor for e2e testing?

If so, try creating the application with `ng new your-application-name`, and then from the root of the project, run `ng add @briebug/cypress-schematic`.

If this doesn't solve your issue, let me know and we'll work to solve it.

**Comment by RyanPnayR** [comment]
@anthonymjones That fixed my issue.

I had to first remove my current cypress.json file and my plugins/index.js file. When I first ran the add I got this 
```
ERROR! cypress.json already exists.
ERROR! cypress/plugins/index.js already exists.
The Schematic workflow failed. See above.

**Comment by anthonymjones** [comment]
Glad that took care of it. Thanks for reaching out!
