### ISSUE TITLE
"ng e2e --prod" against built files

### ISSUE THREAD

**Issue by jayoungers** [briebug/cypress-schematic#45]
**Describe the solution you'd like**
I'm running the e2e process in our CI build, which also runs `ng build --prod` for the resulting artifact.

Is there a way I could build the production files once, then tell cypress to run against those files somehow?

```ts
        "e2e": {
          "builder": "@briebug/cypress-schematic:cypress",
          "options": {
            "devServerTarget": "my-app:serve",
            "watch": true,
            "headless": false
          },
          "configurations": {
            "production": {
              // run server from dist files instead
              "devServerTarget": "my-app:serve:production",
               "watch": false,
              "headless": true
            }
          }
```

**Comment by muuvmuuv** [comment]
Even better would be an option `noBuild: true` that can be added to any configuration. I need this as well for CI to not waste so much time on building the app twice or more...

**Comment by muuvmuuv** [comment]
Since cypress does not serve the build output directory itself nor does `cypress-schematic` which just starts `ng serve`. This is something Angular needs to add to their serve command to skip the building step, see https://stackoverflow.com/questions/40790951/how-to-run-ng-serve-without-building-first.

A workaround would be to spin up a dev server for the build output dir by `cypress-schematic` but this is IMO too much work. This should be core of Angular CLI. Gatsby for example has two commands, one for serving with building and one for just serving build output dir.
